version: '3'
networks:
  net-sslproxy:

services:

  proxy:
    image: "dock1100/haproxy-certbot"
    container_name: sslproxy
    cap_add:
      - NET_ADMIN
    networks:
      - net-sslproxy
    volumes:
      - ./haproxy.cfg.example:/config/haproxy.cfg:ro
      # These settings can be used when one is ready to configure a more permanent deployment
#      - /etc/docker/haproxy/letsencrypt/:/etc/letsencrypt
#      - /etc/docker/haproxy/certs.d/:/usr/local/etc/haproxy/certs.d
#      - /var/log/docker/haproxy/:/var/log/supervisord
    ports:
      - 88:80
      - 8080:8080
      - 443:443


  demo_app:
    container_name: demo_app  # don't use a dash because this becomes the host name
    depends_on:
      - proxy
    image: "demo"
    networks:
      - net-sslproxy
#    volumes:
#      - ./app:/app:ro
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
