version: '3'
networks:
  demo-proxy:

services:

  proxy:
    image: "nginx:latest"
    container_name: nginx
    depends_on:
      - demo_app

    networks:
      - demo-proxy
    ports:
      - 88:80
    volumes:
      - ./example-nginx.cfg:/etc/nginx/conf.d/default.conf

  demo_app:
    container_name: demo_app  # don't use a dash because this becomes the host name
    image: "demo"
    networks:
      - demo-proxy
#    volumes:
#      - ./app:/app:ro
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
